### ISSUE TITLE
Set wavelength voltage sweep ui option throws an error for dream stage

### ISSUE THREAD

**Issue by PetervandenDoel** [SiEPIC/SiEPIC_testcreator#12]
All of the sequence UI options that exist in test creator bring up the menu properly except for the set wavelength voltage sweep option on the dream stage. It throws an error whenever the box is clicked instead of bringing up a user interface menu to define the sequence parameters.

![image](https://github.com/SiEPIC/SiEPIC_testcreator/assets/73015873/89c91df5-d37b-4fb2-a6e7-347890483012)

**Comment by JymBone5** [comment]
this should be fixed now in version 0.1.12, let me know here if there are still issues with is
